apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xinw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xinw
    app.kubernetes.io/part-of: tkrw-pr712-0075-0012-app
  name: devfile-sample-xinw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xinw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xinw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0012-tenant/tkrw-pr712-0075-0012-app/devfile-sample-xinw@sha256:012efa5a390353a8bed0eb4d47ffcae3a184196c61fe097fdcd36f8761e4dfe5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
